### ISSUE TITLE
Gradients of B-Basis Projections

### ISSUE THREAD

**Issue by Basti1211** [ICAMS/python-ace#14]
Hello,

your tool allows obtaining the projections of the B-basis for configurations. Does your tool also support retrieving the gradients of the B-basis functions at specific positions? I need those for a GPR-based approach to construct force kernels.

Best Regards!

**Comment by mikejwaters** [comment]
I think I would also like this feature for my workflow. I'm still learning the internals though.

**Comment by pmrv** [comment]
It'd be nice to have them, but looking at the current code, I guess the issue is that the ace evaluator never explicitly saves them.

If I understand it correctly the relevant parts are [here](https://github.com/ICAMS/python-ace/blob/8b3c6cf19e3152d4599845914c107f4338e97dd9/lib/ace/ace-evaluator/src/ace-evaluator/ace_evaluator.cpp#L568) and [here](https://github.com/ICAMS/python-ace/blob/8b3c6cf19e3152d4599845914c107f4338e97dd9/lib/ace/ace-evaluator/src/ace-evaluator/ace_evaluator.cpp#L586).  In a custom program, it shouldn't too hard to change this part and just drop the multiplication with the `weights*()`, but making it available via the ASE calculator nicely seems to be a bit harder.

**Comment by yury-lysogorskiy** [comment]
We  implemented them recently, just need some time to move it to public branch

**Comment by pmrv** [comment]
I understand that exposing all B basis derivatives is much more memory heavy than doing the summation inline, but at least for my application it would already be enough to get the pairwise forces between atoms.  Though now that I think about it, I'm not sure how you'd define those in terms of higher n-body correlations.  I guess for the virial that the calculator outputs this has to be done somehow?

**Comment by yury-lysogorskiy** [comment]
@pmrv @Basti1211 @mikejwaters @jmgoff   I prototyped linear ACE fit (i.e. by calcualtion of separated B-func derivatives) in this branch https://github.com/ICAMS/python-ace/tree/feature/linear-fit 

* For linear ACE fit: check [examples/linear-fit/Cu2_linear_fit.ipynb](https://github.com/ICAMS/python-ace/blob/feature/linear-fit/examples/linear-fit/Cu2_linear_fit.ipynb)

* For usage in Python: check i.e. this code [here](https://github.com/ICAMS/python-ace/blob/956a86daad59961d9cdaa0f9a03e2fa6bd17f9e1/src/pyace/linearacefit.py#L22C1-L40C45)

* For usage in C++, you can check how these gradients are collected into `forces_bfuncs` [here](https://github.com/ICAMS/python-ace/blob/feature/linear-fit/lib/ace/ace-evaluator/src/extra/ace_calculator.cpp) 
check blocks
```cpp
if (evaluator->compute_b_grad) {
...
}
```

**Comment by mikejwaters** [comment]
Hi @yury-lysogorskiy, sorry for the delay but this is great news! 

Ralf just gave a talk at my university and he spoke very highly of you. If I ever have free time again, maybe I can work on implementing hyperactive learning (also called GOFEE, or uncertainty biased molecular dynamics) with some oversight from you.

**Comment by jmgoff** [comment]
This is excellent, thank you! I've been looking into it some more, and it looks very clean and easy to use. I look forward to adding some of this to LAMMPS.
