### ISSUE TITLE
ladder_step, cycle_step and iter_num 

### ISSUE THREAD

**Issue by zfan2016** [ICAMS/python-ace#42]
Hi, I'm not very sure the meaning of ladder_step, cycle_step and iter_num in the output file of metrics.txt. Could you provide more explanation for them? 

iter_num should be equal to the number of mini-batch of data, right?
ladder_step should be related to Ladder fitting.
But what is cycle_step? why is cycle_step always zero when I was fitting potentials? 
what is the relationship among ladder_step, cycle_step and iter_num?

**Comment by yury-lysogorskiy** [comment]
- `iter_num` is number of minimizer iterations. Because we use  mostly `BFGS` for minimization, it requires full gradient of loss function, which is just sum over mini-batches. 
- `ladder_step` is for hierarchical fitting, shows number of basis set extensions
- `cycle_step`  was used at the beginning but now it is deprecated. Basically for every given ladder step (or single-shot fit) you can apply random noise to the fitted coefficients and try to optimize again with i.e. BFGS. This is somehow similar to "basin-hopping" method.  you can check [these options](https://pacemaker.readthedocs.io/en/latest/pacemaker/inputfile/#fitting_settings)):
```
##(optional) number of consequentive runs of fitting algorithm (for each ladder step), that helps convergence
    #fit_cycles: 1   

    ## starting from second fit_cycle:

    ## applies Gaussian noise with specified relative sigma/mean ratio to all potential trainable coefficients
    #noise_relative_sigma: 1e-3

    ## applies Gaussian noise with specified absolute sigma to all potential trainable coefficients
    #noise_absolute_sigma: 1e-3
```

> what is the relationship among ladder_step, cycle_step and iter_num?
- iter_num - innermost loop variable
- cycle_step
- ladder_step - outermost loop variable

check this pacemaker workflow: https://pacemaker.readthedocs.io/en/latest/pacemaker/workflow/
